
﻿var Drawing={Vertex:null,Point:null,Polyline:null,Polygon:null,Circle:null,Style:null,Painter:null,PainterCanvas:null};(function(){var id=0;function inheritFromConstructor(parent,child){child.prototype=new parent();child.prototype.constructor=child;};function objectPlus(o1,o2){for(var i in o2){o1[i]=o2[i]}
return o1;}
Drawing.Vertex=function(x,y){this.x=x;this.y=y;};function Shape(){this.vertexes=null;}
Shape.prototype=objectPlus(Shape.prototype,{getPerimeter:function(){return"false Shape.prototype.getPerimeter";},getArea:function(){return"false Shape.prototype.GetArea";},resize:function(vertexIndex,multiple){if(vertexIndex>this.vertexes.length-1){return"false";}
var standardVertex=this.vertexes[vertexIndex];for(var i=0;i<this.vertexes.length;i++){this.vertexes[i].x=standardVertex.x-(standardVertex.x-this.vertexes[i].x)*multiple;this.vertexes[i].y=standardVertex.y-(standardVertex.y-this.vertexes[i].y)*multiple;}},move:function(veticalOffset,horizontalOffset){for(var i=0;i<this.vertexes.length;i++){this.vertexes[i].x+=veticalOffset;this.vertexes[i].y+=horizontalOffset;}}});Drawing.Point=function(vertex){vertex=vertex||new Vertex(0,0);this.vertexes=[vertex];this.id=id++;};inheritFromConstructor(Shape,Drawing.Point);Drawing.Point.prototype=objectPlus(Drawing.Point.prototype,{getPerimeter:function(){return 0;},getArea:function(){return 0;},resize:function(multiple){}});Drawing.Polyline=function(vertexes){this.vertexes=vertexes;this.id=id++;};inheritFromConstructor(Shape,Drawing.Polyline);Drawing.Polyline.prototype=objectPlus(Drawing.Polyline.prototype,{getPerimeter:function(){var perimeter=0;for(var i=0;i<this.vertexes.length-1;i++){perimeter+=Math.sqrt(Math.pow(this.vertexes[i+1].x-this.vertexes[i].x,2)+Math.pow(this.vertexes[i+1].y-this.vertexes[i].y,2));}
return perimeter;},getArea:function(){return 0;}});Drawing.Polygon=function(vertexes){this.vertexes=vertexes;this.id=id++;};inheritFromConstructor(Shape,Drawing.Polygon);Drawing.Polygon.prototype=objectPlus(Drawing.Polygon.prototype,{getPerimeter:function(){var perimeter=0;for(var i=0;i<this.vertexes.length-1;i++){perimeter+=Math.sqrt(Math.pow(this.vertexes[i+1].x-this.vertexes[i].x,2)+Math.pow(this.vertexes[i+1].y-this.vertexes[i].y,2));}
perimeter+=Math.sqrt(Math.pow(this.vertexes[0].x-this.vertexes[this.vertexes.length-1].x,2)+Math.pow(this.vertexes[0].y-this.vertexes[this.vertexes.length-1].y,2));return perimeter;},getArea:function(){return"true Polygon.prototype.GetArea";}});Drawing.Circle=function(center,radius){this.vertexes=[center];this.radius=radius;this.id=id++;};inheritFromConstructor(Shape,Drawing.Circle);Drawing.Circle.prototype=objectPlus(Drawing.Circle.prototype,{getPerimeter:function(){return 2*Math.PI*this.radius;},getArea:function(){return Math.PI*Math.pow(this.radius,2);},resize:function(multiple){this.radius*=multiple;}});Drawing.Style=function(borderColor,fillColor,borderWidth){this.borderColor=borderColor;this.fillColor=fillColor||"rgba(0,0,0,0)";this.borderWidth=borderWidth||1;};Drawing.PainterCanvas=function(width,height,backgroundColor){this.width=width;this.height=height;this.backgroundColor=backgroundColor;}
Drawing.PainterCanvas.prototype=objectPlus(Drawing.PainterCanvas.prototype,{clear:function(){c.getContext('2d').clearRect(0,0,this.width,this.height);}});var c=document.createElement('canvas');Drawing.Painter=function(painterCanvas,style){if(painterCanvas.constructor===Drawing.PainterCanvas){c.width=painterCanvas.width;c.height=painterCanvas.height;c.style.background=painterCanvas.backgroundColor;document.body.appendChild(c);}
else if(painterCanvas.constructor===HTMLCanvasElement){c=painterCanvas;}
this.canvas=c;this.cxt=c.getContext('2d');this.style=style||new Style("Black");this.shapes=[];};Drawing.Painter.prototype=objectPlus(Drawing.Painter.prototype,{draw:function(shape){this.setCxtStyle();switch(shape.constructor){case Drawing.Point:this.drawPoint(shape.vertexes[0]);break;case Drawing.Polyline:this.drawPolyline(shape);break;case Drawing.Polygon:this.drawPolygon(shape);break;case Drawing.Circle:this.drawCircle(shape);break;default:return"wrong shape";break;}},drawPoint:function(vertex){return"drawing Point";},drawPolyline:function(polyline){this.cxt.beginPath();this.cxt.moveTo(polyline.vertexes[0].x,polyline.vertexes[0].y);for(var i=1;i<polyline.vertexes.length;i++){this.cxt.lineTo(polyline.vertexes[i].x,polyline.vertexes[i].y);}
this.cxt.stroke();},drawPolygon:function(polygon){this.cxt.beginPath();this.cxt.moveTo(polygon.vertexes[0].x,polygon.vertexes[0].y);for(var i=1;i<polygon.vertexes.length;i++){this.cxt.lineTo(polygon.vertexes[i].x,polygon.vertexes[i].y);}
this.cxt.lineTo(polygon.vertexes[0].x,polygon.vertexes[0].y);this.cxt.closePath();this.cxt.stroke();this.cxt.fill();},drawCircle:function(circle){this.cxt.beginPath();this.cxt.arc(circle.vertexes[0].x,circle.vertexes[0].y,circle.radius,0,2*Math.PI);this.cxt.closePath();this.cxt.stroke();this.cxt.fill();},setCanvas:function(painterCanvas){if(painterCanvas.constructor===Drawing.PainterCanvas){c.width=painterCanvas.width;c.height=painterCanvas.height;c.style.background=painterCanvas.backgroundColor;document.body.appendChild(c);}
else if(painterCanvas.constructor===HTMLCanvasElement){c=painterCanvas;}
this.canvas=c;this.cxt=c.getContext('2d');},setStyle:function(style){this.style=style;this.setCxtStyle();},setCxtStyle:function(){this.cxt.strokeStyle=this.style.borderColor;this.cxt.lineWidth=this.style.borderWidth;this.cxt.fillStyle=this.style.fillColor;}});})();